/*
Copyright (C) 2018 Christoph Schied
Copyright (C) 2019, NVIDIA CORPORATION. All rights reserved.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

#version 460
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

#define GLOBAL_UBO_DESC_SET_IDX 0
#include "global_ubo.h"

#define GLOBAL_TEXTURES_DESC_SET_IDX 1
#include "global_textures.h"

#include "utils.glsl"
#include "asvgf.glsl"
#include "brdf.glsl"

// Bilinear/bilateral interpolation of the LF channel data.
// Kept in sync with the final compositing path from asvgf_atrous.comp.
SH interpolate_lf(sampler2D img_lf_shY, sampler2D img_lf_CoCg, ivec2 ipos)
{
	float depth_center = texelFetch(TEX_PT_VIEW_DEPTH_A, ipos, 0).x;
	float fwidth_depth = texelFetch(TEX_PT_MOTION, ipos, 0).w;
	vec3 geo_normal_center = decode_normal(texelFetch(TEX_PT_GEO_NORMAL_A, ipos, 0).x);

	vec2 pos_lowres = (vec2(ipos) + vec2(0.5)) / GRAD_DWN - vec2(0.5);
	vec2 pos_ld = floor(pos_lowres);
	vec2 subpix = fract(pos_lowres - pos_ld);

	SH sum_lf = init_SH();
	float sum_w = 0.0;

	const ivec2 off[4] = { { 0, 0 }, { 1, 0 }, { 0, 1 }, { 1, 1 } };
	float w[4] = {
		(1.0 - subpix.x) * (1.0 - subpix.y),
		(subpix.x      ) * (1.0 - subpix.y),
		(1.0 - subpix.x) * (subpix.y      ),
		(subpix.x      ) * (subpix.y      )
	};

	for (int i = 0; i < 4; i++)
	{
		ivec2 p_lowres = ivec2(pos_ld) + off[i];
		ivec2 p_hires = p_lowres * GRAD_DWN + ivec2(1);

		float p_depth = texelFetch(TEX_PT_VIEW_DEPTH_A, p_hires, 0).x;
		vec3 p_geo_normal = decode_normal(texelFetch(TEX_PT_GEO_NORMAL_A, p_hires, 0).x);

		float p_w = w[i];
		float dist_depth = abs(p_depth - depth_center) * fwidth_depth;
		p_w *= exp(-dist_depth);
		p_w *= pow(max(0.0, dot(geo_normal_center, p_geo_normal)), 8.0);

		if (p_w > 0.0)
		{
			SH p_lf = load_SH(img_lf_shY, img_lf_CoCg, p_lowres);
			accumulate_SH(sum_lf, p_lf, p_w);
			sum_w += p_w;
		}
	}

	if (sum_w > 0.0)
	{
		float inv_w = 1.0 / sum_w;
		sum_lf.shY *= inv_w;
		sum_lf.CoCg *= inv_w;
	}
	else
	{
		sum_lf = load_SH(TEX_ASVGF_HIST_COLOR_LF_SH_A, TEX_ASVGF_HIST_COLOR_LF_COCG_A, ipos);
	}

	return sum_lf;
}

bool is_fast_path_active()
{
	return global_ubo.pt_fast_path != 0.0;
}

void main()
{
	ivec2 ipos = ivec2(gl_GlobalInvocationID.xy);
	if (ipos.x >= global_ubo.current_gpu_slice_width || ipos.y >= global_ubo.height)
		return;

	SH filtered_lf;
	if (is_fast_path_active())
		filtered_lf = init_SH();
	else
		filtered_lf = interpolate_lf(TEX_ASVGF_ATROUS_PING_LF_SH, TEX_ASVGF_ATROUS_PING_LF_COCG, ipos);
	filtered_lf.shY /= STORAGE_SCALE_LF;
	filtered_lf.CoCg /= STORAGE_SCALE_LF;

	vec3 filtered_hf = max(texelFetch(TEX_NRD_OUT_DIFF_RADIANCE_HITDIST, ipos, 0).rgb, vec3(0.0));
	filtered_hf += unpackRGBE(texelFetch(TEX_ASVGF_ATROUS_PONG_HF, ipos, 0).x) / STORAGE_SCALE_HF;
	vec3 filtered_spec = max(texelFetch(TEX_NRD_OUT_SPEC_RADIANCE_HITDIST, ipos, 0).rgb, vec3(0.0));
	filtered_spec += unpackRGBE(texelFetch(TEX_ASVGF_ATROUS_PING_HF, ipos, 0).x) / STORAGE_SCALE_SPEC;

	vec3 normal = decode_normal(texelFetch(TEX_PT_NORMAL_A, ipos, 0).x);
	vec4 base_color = texelFetch(TEX_PT_BASE_COLOR_A, ipos, 0);
	vec2 metallic_roughness = texelFetch(TEX_PT_METALLIC_A, ipos, 0).rg;
	float specular_factor = base_color.a;
	float checkerboard_flags = texelFetch(TEX_PT_VIEW_DIRECTION, ipos, 0).a;
	float metallic = metallic_roughness.x;
	float roughness = metallic_roughness.y;

#if ENABLE_SH
	if (global_ubo.pt_fake_roughness_threshold < 1.0)
	{
		float fake_specular_weight = smoothstep(
			global_ubo.pt_fake_roughness_threshold,
			global_ubo.pt_fake_roughness_threshold + 0.1,
			roughness);

		if (filtered_lf.shY.w > 0 && fake_specular_weight > 0)
		{
			vec3 view_direction = texelFetch(TEX_PT_VIEW_DIRECTION, ipos, 0).xyz;
			vec3 incoming_direction = filtered_lf.shY.xyz / filtered_lf.shY.w * (0.282095 / 0.488603);
			float incoming_len = length(incoming_direction);
			float directionality = incoming_len;
			float scale = 1.0;

			if (directionality >= 1.0)
			{
				incoming_direction /= incoming_len;
			}
			else
			{
				incoming_direction = mix(reflect(view_direction, normal), incoming_direction / (incoming_len + 1e-6), vec3(directionality));
				roughness = mix(1.0, roughness, pow(directionality, 3.0));
				scale = pow(roughness + 1.0, 3.0);
			}

			vec3 color = SH_to_irradiance(filtered_lf);

			vec3 albedo, base_reflectivity;
			get_reflectivity(base_color.rgb, metallic, albedo, base_reflectivity);

			vec3 F;
			vec3 brdf = GGX_times_NdotL(view_direction, incoming_direction, normal, roughness, base_reflectivity, 0.0, specular_factor, F);

			vec3 fake_specular = color * fake_specular_weight * brdf * scale;
			fake_specular = demodulate_specular(base_reflectivity, fake_specular);

			filtered_spec += fake_specular;
		}
	}
#endif

	vec3 projected_lf = project_SH_irradiance(filtered_lf, normal);
	vec4 transparent = texelFetch(TEX_PT_TRANSPARENT, ipos, 0);
	vec3 throughput = texelFetch(TEX_PT_THROUGHPUT, ipos, 0).rgb;
	vec3 final_color = composite_color(base_color.rgb, metallic, throughput, projected_lf, filtered_hf, filtered_spec, transparent);

	if (global_ubo.flt_show_gradients != 0 && !is_fast_path_active())
	{
		float gradient_lf = texelFetch(TEX_ASVGF_GRAD_LF_PONG, ipos / GRAD_DWN, 0).r;
		vec2 gradient_hf_spec = texelFetch(TEX_ASVGF_GRAD_HF_SPEC_PONG, ipos / GRAD_DWN, 0).rg;
		final_color.r += gradient_lf * global_ubo.flt_scale_lf;
		final_color.g += gradient_hf_spec.x * global_ubo.flt_scale_hf;
		final_color.b += gradient_hf_spec.y * global_ubo.flt_scale_spec;
	}

	final_color *= STORAGE_SCALE_HDR;
	imageStore(IMG_ASVGF_COLOR, ipos, vec4(final_color, checkerboard_flags));
}
